### ISSUE TITLE
App crashes on Heroku

### ISSUE THREAD

**Issue by bgmat** [sendgrid/sendgrid-ruby#246]
Hi

I implemented a simple app to test sendgrid, following the instructions.
The app works on my local server, no issues whatsoever.
Once I deploy to heroku, any request crashes the app with the logs below.

2017-10-27T10:39:29.110941+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 47424 -e production`
2017-10-27T10:39:32.304057+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail.rb:3:in `<top (required)>': Mail is not a module (TypeError)
2017-10-27T10:39:32.304074+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
2017-10-27T10:39:32.304075+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
2017-10-27T10:39:32.304075+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
2017-10-27T10:39:32.304076+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
2017-10-27T10:39:32.304077+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:1:in `<top (required)>'
2017-10-27T10:39:32.304077+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
2017-10-27T10:39:32.304078+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
2017-10-27T10:39:32.304078+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
2017-10-27T10:39:32.304079+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
2017-10-27T10:39:32.304095+00:00 app[web.1]: 	from /app/app/mailers/application_mailer.rb:1:in `<top (required)>'
2017-10-27T10:39:32.304096+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
2017-10-27T10:39:32.304096+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
2017-10-27T10:39:32.304097+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
2017-10-27T10:39:32.304097+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
2017-10-27T10:39:32.304103+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:379:in `block in require_or_load'
2017-10-27T10:39:32.304104+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
2017-10-27T10:39:32.304105+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
2017-10-27T10:39:32.304105+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
2017-10-27T10:39:32.304106+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
2017-10-27T10:39:32.304107+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
2017-10-27T10:39:32.304107+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
2017-10-27T10:39:32.304108+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
2017-10-27T10:39:32.304108+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
2017-10-27T10:39:32.304109+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
2017-10-27T10:39:32.304110+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
2017-10-27T10:39:32.304114+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
2017-10-27T10:39:32.304110+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
2017-10-27T10:39:32.304114+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
2017-10-27T10:39:32.304115+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:354:in `eager_load!'
2017-10-27T10:39:32.304116+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `each'
2017-10-27T10:39:32.304116+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
2017-10-27T10:39:32.304117+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
2017-10-27T10:39:32.304118+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
2017-10-27T10:39:32.304118+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
2017-10-27T10:39:32.304119+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
2017-10-27T10:39:32.304119+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2017-10-27T10:39:32.304120+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
2017-10-27T10:39:32.304120+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
2017-10-27T10:39:32.304121+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each'
2017-10-27T10:39:32.304121+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `call'
2017-10-27T10:39:32.304122+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
2017-10-27T10:39:32.304122+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
2017-10-27T10:39:32.304123+00:00 app[web.1]: 	from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
2017-10-27T10:39:32.304123+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
2017-10-27T10:39:32.304124+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
2017-10-27T10:39:32.304125+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<top (required)>'
2017-10-27T10:39:32.304126+00:00 app[web.1]: 	from config.ru:3:in `require_relative'
2017-10-27T10:39:32.304126+00:00 app[web.1]: 	from config.ru:3:in `block in <main>'
2017-10-27T10:39:32.304127+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
2017-10-27T10:39:32.304128+00:00 app[web.1]: 	from config.ru:in `new'
2017-10-27T10:39:32.304127+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
2017-10-27T10:39:32.304128+00:00 app[web.1]: 	from config.ru:in `<main>'
2017-10-27T10:39:32.304129+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
2017-10-27T10:39:32.304130+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
2017-10-27T10:39:32.304130+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
2017-10-27T10:39:32.304131+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
2017-10-27T10:39:32.304132+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
2017-10-27T10:39:32.304132+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:24:in `app'
2017-10-27T10:39:32.304135+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
2017-10-27T10:39:32.304136+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:283:in `start'
2017-10-27T10:39:32.304136+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:44:in `start'
2017-10-27T10:39:32.304137+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:135:in `block in perform'
2017-10-27T10:39:32.304138+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
2017-10-27T10:39:32.304138+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
2017-10-27T10:39:32.304139+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
2017-10-27T10:39:32.304140+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
2017-10-27T10:39:32.304141+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
2017-10-27T10:39:32.304140+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
2017-10-27T10:39:32.304142+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
2017-10-27T10:39:32.304142+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
2017-10-27T10:39:32.304143+00:00 app[web.1]: 	from bin/rails:4:in `require'
2017-10-27T10:39:32.304145+00:00 app[web.1]: 	from bin/rails:4:in `<main>'
2017-10-27T10:39:32.308180+00:00 app[web.1]: => Booting Puma
2017-10-27T10:39:32.308182+00:00 app[web.1]: => Rails 5.1.4 application starting in production 
2017-10-27T10:39:32.308183+00:00 app[web.1]: => Run `rails server -h` for more startup options
2017-10-27T10:39:32.308183+00:00 app[web.1]: Exiting
2017-10-27T10:39:32.415526+00:00 heroku[web.1]: State changed from starting to crashed
2017-10-27T10:39:32.400072+00:00 heroku[web.1]: Process exited with status 1
2017-10-27T10:39:46.659084+00:00 heroku[router]: at=error code=H10 desc="App crashed"

* Ruby Version: 2.4.2

**Comment by mbernier** [comment]
Is this related to this? https://github.com/sendgrid/sendgrid-ruby/blob/master/TROUBLESHOOTING.md#rails-specifics

**Comment by bgmat** [comment]
@mbernier 
Thank you for pointing to this page!
The following paragraph solved the issue:
"Possibility of a namespace collision between the sendgrid class Email and your own defined Email class. To avoid these issues, you can skip the include SendGrid line and use the SendGrid:: prefix for Email. Please see this SO answer for specifics."

**Comment by mbernier** [comment]
Ahhhh yeah! Nice!! @GustavoCaso [here](https://github.com/sendgrid/sendgrid-ruby/blame/a953199b0c3f1c90fadebdf57d9820521ab4b15c/TROUBLESHOOTING.md#L118) and @orthodex [here](https://github.com/sendgrid/sendgrid-ruby/blame/master/TROUBLESHOOTING.md#L120) FTW

@bgmat - Would it make sense to update the Heroku example to just use the suggested namespace?

**Comment by bgmat** [comment]
@mbernier I think it would be useful at lease to add a note to this possible issue, because the way the app is behaving and the logs you get are not very suggestive

**Comment by eyewritecode** [comment]
Hey @thinkingserious, what would be the optimal solution for this? It looks like the TROUBLESHOOTING documents has the answer but i don't know what a PR for this issue would be?
