### ISSUE TITLE
NoMethodError: undefined method `<<' for nil:NilClass (Only in production!)

### ISSUE THREAD

**Issue by coderdave** [sendgrid/sendgrid-ruby#349]
#### Issue Summary

When running the example, I get "NoMethodError: undefined method `<<' for nil:NilClass".

```ruby
NoMethodError: undefined method `<<' for nil:NilClass
	from /app/vendor/bundle/ruby/2.4.0/gems/sendgrid-ruby-5.3.0/lib/sendgrid/helpers/mail/mail.rb:56:in `add_personalization'
	from (irb):9
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```
The real crazy thing is that I only get this in production!

When I examine `mail`, `@personalizations` is `nil`!

```ruby
irb(main):014:0> mail
=> #<SendGrid::Mail:0x00000005329ad8 @from=#<SendGrid::Email:0x000000053cde80 @email="test@example.com", @name=nil>, @subject="Hello World from the SendGrid Ruby Library", @personalizations=nil, @contents=nil, @attachments=nil, @template_id=nil, @sections=nil, @headers=nil, @categories=nil, @custom_args=nil, @send_at=nil, @batch_id=nil, @asm=nil, @ip_pool_name=nil, @mail_settings=nil, @tracking_settings=nil, @reply_to=nil>
```

#### Steps to Reproduce

1. Ran the kitchen_sink example

#### Technical details:

* sendgrid-ruby Version: 5.3.0
* Ruby Version: 2.4.0

**Comment by thinkingserious** [comment]
Hello @coderdave,

Could you provide some detail about your production environment so that I may try and duplicate this issue?

Thanks!

With Best Regards,

Elmer
